Add more service names in donet-package.csv
jongio/azure-sdk pull request #9
Opened 2020-11-12 10:50 UTC by v-xuto

1. Add more service names in donet-package.csv.

@jongio for notification.

2020-11-14 03:23 UTC, jongio requested changes

2020-11-14 03:23 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Azure.Data.SchemaRegistry","","1.0.0-beta.2","Event Hubs - Schema Registry","Event Hubs","schemaregistry","","","client","true","",""
why event hubs?

2020-11-14 03:23 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Azure.ResourceManager.Dns","","1.0.0-preview.1","Resource Management - DNS","DNS zones","dns","","","mgmt","true","",""
why zones?

2020-11-14 03:23 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Azure.ResourceManager.Network","","1.0.0-preview.2","Resource Management - Network","Virtual Network","network","","","mgmt","true","",""
Why virtual?

2020-11-14 03:23 UTC, jongio commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.Azure.Management.HDInsight","6.0.0","","Management - HdInsight","HdInsight","hdinsight","https://docs.microsoft.com/dotnet/api/overview/azure/hdinsight","NA","mgmt","false","",""
HD

2020-11-16 02:52 UTC, v-xuto commented on _data/releases/latest/dotnet-packages.csv
> +"Microsoft.Azure.Management.HDInsight","6.0.0","","Management - HdInsight","HdInsight","hdinsight","https://docs.microsoft.com/dotnet/api/overview/azure/hdinsight","NA","mgmt","false","",""
I have updated it.

2020-11-16 02:53 UTC, v-xuto commented on _data/releases/latest/dotnet-packages.csv
> +"Azure.ResourceManager.Dns","","1.0.0-preview.1","Resource Management - DNS","DNS zones","dns","","","mgmt","true","",""
I have updated it.

2020-11-16 02:54 UTC, v-xuto commented on _data/releases/latest/dotnet-packages.csv
> +"Azure.ResourceManager.Network","","1.0.0-preview.2","Resource Management - Network","Virtual Network","network","","","mgmt","true","",""
Refer this link: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/virtual-network?view=azure-dotnet.

2020-11-16 02:56 UTC, v-xuto commented on _data/releases/latest/dotnet-packages.csv
> +"Azure.Data.SchemaRegistry","","1.0.0-beta.2","Event Hubs - Schema Registry","Event Hubs","schemaregistry","","","client","true","",""
Refer this link: https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview

2020-11-18 09:45 UTC, v-xuto commented
@jongio - We have updated the csv files about four languages (donet, java, js and python). Please Review.

2020-11-23 02:00 UTC, jongio requested changes

2020-11-23 02:02 UTC, jongio commented
@v-xuto - Please retarget this to azure-sdk:master instead of jongio:more-services  Thanks

2020-11-24 07:25 UTC, closed without merging